/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memapplication;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.*;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Romi
 */
public class Interfaz extends javax.swing.JFrame {
     //------manejador de memoria--------
     Manejador manejador;
     int nroPaginas_inicial;
     JTextArea[] marcos;
     int cont_de_proceso =0;
     JTextArea[] ids;
     JTextArea[] totalpgs;
     JTextArea[] totalrams;
     JTextArea[] nrodiscos;
     JTextArea[] estados;  
     
     JTextArea[] virtualids;
     JTextArea[] virtualpags;
      //prueba para guardar en archivo---
     String [] cont_para_paginas_escribir= new String[100];
     int indice_cont_de_pag=0;     
     int marcosGlobal=0;
     int fallo_de_pagina=0;
     String patchGlobal="";
     //----------------------------------
    @Override
    protected String paramString() {
        return super.paramString(); //To change body of generated methods, choose Tools | Templates.
    }
    //-------------------------------------- 
    /**     * Creates new form  */
    public Interfaz() {
        initComponents();
        createMenuBar();       
        this.setResizable(false);//que no se estire
        this.setDefaultCloseOperation(EXIT_ON_CLOSE); 
        this.deshabilitar();
        setLocationRelativeTo(null);//centrar proyecto
        jLabe_lOrden.setForeground(Color.gray);   
        Textarea_Orden.setEnabled(false);
    }

    private void createMenuBar(){
        //this.barraMenu.setHelpMenu(manual);  
        this.boton_algoritmos.setVisible(false);
         this.jMenu_Achivo.add(this.boton_abrir);
         
         this.jMenu_Achivo.add(this.boton_guardar);
         this.jMenu_Edicion.add(limpiar);
         this.jMenu_algoritmo.add("FIFO");
         this.jMenu_Ayuda.add(boton_manual);
         //boton_abrir.addActionListener(new ManejadorBotonAbrir());
    }

    /**
     * This method is  from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textarea4 = new javax.swing.JTextArea();
        siguiente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ejecutar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        procesador = new javax.swing.JTextArea();
        boton_algoritmos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ram = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_nroDePagina = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Textarea_nroPaginas = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        crearProceso = new javax.swing.JButton();
        jLabel_cont_proceso = new javax.swing.JLabel();
        radioButton_opcion1 = new javax.swing.JRadioButton();
        radioButton_opcion2 = new javax.swing.JRadioButton();
        jLabe_lOrden = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Textarea_Orden = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        Jbutton_ayuda = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane15 = new javax.swing.JScrollPane();
        Textarea_nombreProceso = new javax.swing.JTextArea();
        jLabel_nroDePagina2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        id = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        totalpg = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        totalram = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        estado = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        nrodisco = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        virtualid = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        virtualpag = new javax.swing.JPanel();
        boton_manual = new javax.swing.JButton();
        boton_abrir = new javax.swing.JButton();
        boton_guardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane11 = new javax.swing.JScrollPane();
        textarea00 = new javax.swing.JTextArea();
        crearMarco = new javax.swing.JButton();
        jLabel_nroDePagina1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jMenu_Achivo = new javax.swing.JMenu();
        jMenu_Edicion = new javax.swing.JMenu();
        jMenu_algoritmo = new javax.swing.JMenu();
        jMenu_Ayuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("MEMORIA RAM");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("PROCESADOR");

        textarea3.setColumns(20);
        textarea3.setLineWrap(true);
        jScrollPane2.setViewportView(textarea3);

        textarea4.setColumns(20);
        textarea4.setLineWrap(true);
        jScrollPane3.setViewportView(textarea4);

        siguiente.setText("EJECUTAR SIGUIENTE");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        jLabel3.setText("INDIQUE NUMERO DE PROCESO");

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        jLabel4.setText("INDIQUE NUMERO DE PAGINA");

        ejecutar.setText("EJECUTAR PAG INDICADA");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("MEMORIA VIRTUAL");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("LISTADO DE PROCESOS");

        jLabel8.setText("ID");

        jLabel9.setText("Total pg ");

        jLabel10.setText("Pag. Ram");

        jLabel11.setText("Pag. Disco");

        jLabel12.setText("Estado");

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        procesador.setColumns(20);
        procesador.setLineWrap(true);
        jScrollPane5.setViewportView(procesador);

        boton_algoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO" }));
        boton_algoritmos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton_algoritmosItemStateChanged(evt);
            }
        });
        boton_algoritmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_algoritmosActionPerformed(evt);
            }
        });

        ram.setBackground(new java.awt.Color(255, 255, 255));
        ram.setAutoscrolls(true);
        ram.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(ram);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nroDePagina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_nroDePagina.setText("Nombre del Proceso");
        jPanel1.add(jLabel_nroDePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        Textarea_nroPaginas.setWrapStyleWord(true);
        Textarea_nroPaginas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane7.setViewportView(Textarea_nroPaginas);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 40, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel13.setText("CREACION DE PROCESOS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, -1));

        crearProceso.setText("::CREAR PROCESO::");
        crearProceso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(crearProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 155, 30));

        jLabel_cont_proceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_cont_proceso.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_cont_proceso.setText("0");
        jPanel1.add(jLabel_cont_proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 20, -1));

        buttonGroup1.add(radioButton_opcion1);
        radioButton_opcion1.setSelected(true);
        radioButton_opcion1.setText("Por defecto");
        radioButton_opcion1.setVerifyInputWhenFocusTarget(false);
        radioButton_opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_opcion1ActionPerformed(evt);
            }
        });
        jPanel1.add(radioButton_opcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        buttonGroup1.add(radioButton_opcion2);
        radioButton_opcion2.setText("Personalizada");
        radioButton_opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_opcion2ActionPerformed(evt);
            }
        });
        jPanel1.add(radioButton_opcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabe_lOrden.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabe_lOrden.setText("Orden");
        jPanel1.add(jLabe_lOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Textarea_Orden.setColumns(20);
        Textarea_Orden.setLineWrap(true);
        Textarea_Orden.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane9.setViewportView(Textarea_Orden);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 255));
        jLabel15.setText("EJEMPLO: 1-3-0-2");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        Jbutton_ayuda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jbutton_ayuda.setForeground(new java.awt.Color(255, 102, 51));
        Jbutton_ayuda.setText("?");
        Jbutton_ayuda.setToolTipText("Ayuda!");
        Jbutton_ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jbutton_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbutton_ayudaActionPerformed(evt);
            }
        });
        jPanel1.add(Jbutton_ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, -1));

        Textarea_nombreProceso.setWrapStyleWord(true);
        Textarea_nombreProceso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane15.setViewportView(Textarea_nombreProceso);

        jPanel1.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 120, 30));

        jLabel_nroDePagina2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_nroDePagina2.setText("Cantidad de páginas del Proceso:");
        jPanel1.add(jLabel_nroDePagina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setToolTipText("");
        id.setAutoscrolls(true);
        id.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane4.setViewportView(id);

        totalpg.setBackground(new java.awt.Color(255, 255, 255));
        totalpg.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane8.setViewportView(totalpg);

        totalram.setBackground(new java.awt.Color(255, 255, 255));
        totalram.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane10.setViewportView(totalram);

        estado.setBackground(new java.awt.Color(255, 255, 255));
        estado.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane12.setViewportView(estado);

        nrodisco.setBackground(new java.awt.Color(255, 255, 255));
        nrodisco.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane13.setViewportView(nrodisco);

        virtualid.setBackground(new java.awt.Color(255, 255, 255));
        virtualid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        virtualid.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane14.setViewportView(virtualid);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("ID del Proceso");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("NUMERO de Pagina");

        virtualpag.setBackground(new java.awt.Color(255, 255, 255));
        virtualpag.setLayout(new java.awt.GridLayout(0, 2));
        jScrollPane6.setViewportView(virtualpag);

        boton_manual.setText("MANUAL");
        boton_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_manualActionPerformed(evt);
            }
        });

        boton_abrir.setText("Mostrar");
        boton_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_abrirActionPerformed(evt);
            }
        });

        boton_guardar.setText("Guardar");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setText("CREACION DE MARCOS EN MEMORIA RAM");

        textarea00.setColumns(20);
        textarea00.setLineWrap(true);
        textarea00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane11.setViewportView(textarea00);

        crearMarco.setText("::Crear Marcos::");
        crearMarco.setToolTipText("si no ingresa un valor, se crean aut. 10 marcos");
        crearMarco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMarcoActionPerformed(evt);
            }
        });

        jLabel_nroDePagina1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_nroDePagina1.setText("Ingrese cantidad de Marcos:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(81, 81, 81))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_nroDePagina1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crearMarco, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(202, 202, 202))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(30, 30, 30)
                .addComponent(jLabel_nroDePagina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane11)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(crearMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memapplication/iconfinder_Data-08_4203014.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("SIMULADOR DE MEMORIA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jMenu_Achivo.setText("Archivo");
        barraMenu.add(jMenu_Achivo);

        jMenu_Edicion.setText("Edición");
        barraMenu.add(jMenu_Edicion);

        jMenu_algoritmo.setText("Algoritmo");
        jMenu_algoritmo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu_algoritmoItemStateChanged(evt);
            }
        });
        jMenu_algoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_algoritmoActionPerformed(evt);
            }
        });
        barraMenu.add(jMenu_algoritmo);

        jMenu_Ayuda.setText("Ayuda");
        jMenu_Ayuda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu_AyudaItemStateChanged(evt);
            }
        });
        jMenu_Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_AyudaActionPerformed(evt);
            }
        });
        barraMenu.add(jMenu_Ayuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2)
                                            .addComponent(siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ejecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jScrollPane5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_manual, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jLabel8)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(33, 33, 33)))))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_guardar)
                        .addGap(61, 61, 61)
                        .addComponent(limpiar)
                        .addGap(94, 94, 94)
                        .addComponent(boton_algoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limpiar)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boton_algoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton_manual))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boton_abrir)
                                .addComponent(boton_guardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel8)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10)
                                    .addComponent(jScrollPane8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(siguiente)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel3)
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(ejecutar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane6))
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane12)
                                    .addComponent(jScrollPane13)))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        this.manejador.Ejecutar();
        
    }//GEN-LAST:event_siguienteActionPerformed
    
    //////////////////////ESTA FUNCION ES PARA INDICAR ALGUN NUMERO DE PROCESO EN PARTICULAR//////////////////
    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        // TODO add your handling code here:
        
        textarea3.setText(textarea3.getText().trim());
        textarea4.setText(textarea4.getText().trim());
                   //text4---> pagina
                   //text3---> proceso
                   String ss=this.textarea3.getText();
                   if (ss.equals("")) {
                           JOptionPane.showMessageDialog(null,"INGRESE NUMERO DE PROCESO");
                           return;
                 }
                   String sss=this.textarea4.getText();
                   if (sss.equals("")) {
                           JOptionPane.showMessageDialog(null,"INGRESE NUMERO DE PAGINA");
                           return;
                    }
                   
                   int idProc=Integer.parseInt(this.textarea3.getText());
                   int nroPag=Integer.parseInt(this.textarea4.getText());
                   
                   System.out.println("nro proceso:_"+idProc+"nro pagina:_"+nroPag);
                   this.manejador.Ejecutar2(idProc, nroPag);
                   
                   textarea3.setText("");
                   textarea4.setText("");
                   fallo_de_pagina++;
                   
    }//GEN-LAST:event_ejecutarActionPerformed

    private void boton_algoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_algoritmosActionPerformed
            
        // TODO add your handling code here:
        String algoritmo=(String) boton_algoritmos.getSelectedItem();
        boton_algoritmos.getSelectedItem();
            if(algoritmo.equals("FIFO")){
                this.manejador.Ejecutar();
            }
            if (algoritmo.equals("LRU")){
            
        
            }
    }//GEN-LAST:event_boton_algoritmosActionPerformed

    ///////////////////////////////////////////////////
        ///BOTON DE ABRIR////
private String abrirArchivo() {
     //TODO DESHABILITADO DIRECTAMENTE CREE UNA CLASE "LEER", MOSTRAR ES SOLO UN JPANEL CON UN TEXTAREA DONDE SE MUESTRA LO QUE SE ABRE
     
   /**llamamos el metodo que permite cargar la ventana*/
   //JFileChooser buscador=new JFileChooser();
   //buscador.showOpenDialog(buscador);
   
   try{
   //de buscador va a seleccionar un archivo y cuando lo seleccione se active absolute patch
      //es decir q patch almacena la ruta de acceso
        
       // String patchGlobal = buscador.getSelectedFile().getAbsolutePath();
        //FileInputStream archivo = new FileInputStream(patchGlobal);
        
      //  System.out.println("variable patch tiene :"+patchGlobal);
        
      //  if (patchGlobal != ""){         
       //         DataInputStream entrada = new DataInputStream(archivo);
                //BufferedReader buffer = new BufferedReader(new InputStreamReader(entrada));
                //   Mostrar_texto.setText();
                
                
                  //comentado en este caso se uso para abrir el archivo guardado en el programa para seguir ejecutandolo
                /*String[] lineas2=new String[200];
                String marco=buffer.readLine();
                int marcos=Integer.parseInt(marco);
                int i=0;
                while((lineas2[i]=buffer.readLine()) != null) {  
                        System.out.println(lineas2[i]);
                        i++;
                } 
                int cantidad=i/9;
                i=0;   
                int k=0;
                Go(marcos);
                while (i<cantidad){                    
                    this.manejador.crearProceso(Integer.parseInt(lineas2[k]),this.Textarea_nombreProceso.getText());
                    this.manejador.ImprimirProcesos();
                    this.manejador.ImprimirMemVirtual();
                    this.manejador.ImprimirMemRAM();                       
                    i++;
                    k=k+9;
                }
                siguiente.setEnabled(true);
                cont_de_proceso=cantidad;
                jLabel_cont_proceso.setText(String.valueOf(cont_de_proceso));
                */
              //  entrada.close();
       // }
       // else{
           
        //ver que se hace aca!!!!
       // }
  }catch(Exception e){     
     //JOptionPane.showMessageDialog(null,"ERROR AL ABRIR");
      e.printStackTrace();
          
  }
   radioButton_opcion1.setSelected(true);
   //crearMarco.setEnabled(false);
   crearProceso.setEnabled(true);
  return(null);
  }
    /////////////////////BOTON GUARDAR///////////////////////
         private void guardarArchivo(int cantidad) {
               System.out.println("la cantidad de marcos es: "+textarea00.getText());
             JFileChooser guardarComo = new JFileChooser();
             guardarComo.setApproveButtonText("Guardar");
             guardarComo.showSaveDialog(null);
             File archivo = new File(guardarComo.getSelectedFile()+".txt");
             try{
             BufferedWriter salida = new BufferedWriter(new FileWriter(archivo));
             
             salida.write("CANTIDAD DE MARCOS ES :"+textarea00.getText());
             salida.newLine();
             salida.write("---------------------------------------------------------I");
             salida.newLine();
             for(int i=0;i<cantidad;i++){ 
               
             //salida.write(marcos[i].getText());
             //salida.write(cont_para_paginas_escribir[i]);
             //salida.newLine();
             //salida.write(manejador.listaDeProcesos().getNombre());//siempre muestra el mismo por que esta parado en el mismo lugar
             //salida.write(Integer.toString(i));//contador de procesos
            // salida.newLine();
             //////////////////////
             if(Integer.parseInt(cont_para_paginas_escribir[i]) > 2){
             //while cont_para_paginas_escribir[i] {
             ////////////////////////
             //salida.write(virtualids[i].getText());
             //salida.newLine();
            // salida.write(virtualpags[i].getText());
            // salida.newLine();
            // }
             }  
             
             salida.write("ID DEL PROCESO :"+ids[i].getText());
             salida.newLine();
             salida.write("TOTAL PAGINAS DEL PROCESO :"+totalpgs[i].getText());
             salida.newLine();
             salida.write("TOTAL PAGINAS EN RAM :"+totalrams[i].getText());
             salida.newLine();
             salida.write("TOTAL PAGINAS EN DISCO :"+nrodiscos[i].getText());
             salida.newLine();
             salida.write("ESTADO DEL PROCESO :"+estados[i].getText());
             salida.newLine();
             salida.write("---------------------------------------------------------I");
             salida.newLine();
             }
             salida.close();
             }catch (Exception e){
             JOptionPane.showMessageDialog(null,"ERROR AL GUARDAR");
 }
         }  
    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
     guardarArchivo(cont_de_proceso);        
    }//GEN-LAST:event_boton_guardarActionPerformed


///////////////////////BOTON LIMPIAR ////////////////////////////
    private void limpiar(){
    Textarea_nombreProceso.setText(null);
    textarea00.setText(null);
    textarea00.setEditable(true);
    textarea00.setEnabled(true);
    textarea3.setText(null);
    textarea4.setText(null);
    procesador.setText(null);
    procesador.setBorder(null);
    Textarea_nroPaginas.setText(null);
    Textarea_Orden.setText(null);
    ram.removeAll();
    ram.repaint();
    id.removeAll();
    id.repaint();
    totalpg.removeAll();
    totalpg.repaint();
    totalram.removeAll();
    totalram.repaint();
    nrodisco.removeAll();
    nrodisco.repaint();
    estado.removeAll();
    estado.repaint();
    id.removeAll();
    id.repaint();
    virtualpag.removeAll();
    virtualpag.repaint(); 
    deshabilitar();
    cont_de_proceso = 0 ;
    buttonGroup1.clearSelection();
    jLabel_nroDePagina.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLabe_lOrden.setForeground(Color.black);
    crearMarco.setEnabled(true);
    jLabel_cont_proceso.setText("0");
    
     }
    
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
               // Clear();
               limpiar();
               radioButton_opcion1.setSelected(true);
               
                
                       
    }//GEN-LAST:event_limpiarActionPerformed
public void Go(int nroMarcos){
    
           manejador=new Manejador(nroMarcos,this);
           //this.ram.setLayout(new  GridLayout(1,3));
           this.marcos=new JTextArea[nroMarcos];
           
                
        
                int i=0;
                while(i<nroMarcos){
                marcos[i]=new JTextArea("marco "+i);
                marcos[i].setEditable(true);
		marcos[i].setLineWrap(true);
		marcos[i].setWrapStyleWord(true);
                marcos[i].setFont(new Font("Arial ", Font.BOLD,16));
                marcos[i].setBorder(BorderFactory.createLineBorder(Color.black));
                marcos[i].setBackground(Color.white);
                marcos[i].setForeground(Color.blue);
                i++;
                }
                i=0;
                while(i<nroMarcos){
                     ram.add(marcos[i]);
                     i++;
                }
                ram.updateUI();
                 ///////////////memoria virtual////////////////////////////////////////
                virtualids=new JTextArea[100];
                virtualpags=new JTextArea[100];
                int k=0;
                   while (k<100)
                {
                  virtualids[k]=new JTextArea();
                  virtualpags[k]=new JTextArea();
                  
                  virtualids[k].setEditable(true);
		  virtualids[k].setLineWrap(true);
		  virtualids[k].setWrapStyleWord(true);
                  virtualids[k].setFont(new Font("Arial ", Font.BOLD, 18));
                  virtualids[k].setBorder(BorderFactory.createLineBorder(Color.black));
                  virtualpags[k].setEditable(true);
		  virtualpags[k].setLineWrap(true);
		  virtualpags[k].setWrapStyleWord(true);
                  virtualpags[k].setFont(new Font("Arial ", Font.BOLD, 18));
                  virtualpags[k].setBorder(BorderFactory.createLineBorder(Color.black));
                  virtualpags[k].setForeground(Color.red);
                  virtualpag.add(virtualids[k]);
                  virtualpag.add(virtualpags[k]);
                  k++;
                }
                 
                 virtualid.updateUI();
                 virtualpag.updateUI();
                 ////////////////////////////////////////////////////////////////////////////
                               
             int j=0;
                this.ids=new JTextArea[100];
                this.totalpgs=new JTextArea[100];
                this.totalrams=new JTextArea[100];
                this.nrodiscos=new JTextArea[100];
                this.estados=new JTextArea[100];
                
                
                
                while (j<100)
                {
                  ids[j]=new JTextArea();
                  totalpgs[j]=new JTextArea();
                  totalrams[j]=new JTextArea();
                  nrodiscos[j]=new JTextArea();
                  estados[j]=new JTextArea();
                  ids[j].setEditable(true);
		  ids[j].setLineWrap(true);
		  ids[j].setWrapStyleWord(true);
                  ids[j].setFont(new Font("Arial ", Font.BOLD, 12));
                  ids[j].setBorder(BorderFactory.createLineBorder(Color.black));
                  totalpgs[j].setEditable(true);
		  totalpgs[j].setLineWrap(true);
		  totalpgs[j].setWrapStyleWord(true);
                  totalpgs[j].setFont(new Font("Arial ", Font.BOLD, 12));
                  totalpgs[j].setBorder(BorderFactory.createLineBorder(Color.black));
                  totalrams[j].setEditable(true);
		  totalrams[j].setLineWrap(true);
		  totalrams[j].setWrapStyleWord(true);
                  totalrams[j].setFont(new Font("Arial ", Font.BOLD, 12));
                  totalrams[j].setBorder(BorderFactory.createLineBorder(Color.black));
                  nrodiscos[j].setEditable(true);
		  nrodiscos[j].setLineWrap(true);
		  nrodiscos[j].setWrapStyleWord(true);
                  nrodiscos[j].setFont(new Font("Arial ", Font.BOLD, 12));
                  nrodiscos[j].setBorder(BorderFactory.createLineBorder(Color.black));
                  estados[j].setEditable(true);
		  estados[j].setLineWrap(true);
		  estados[j].setWrapStyleWord(true);
                  estados[j].setFont(new Font("Arial ", Font.BOLD, 12));
                  estados[j].setForeground(Color.blue);
                  estados[j].setBorder(BorderFactory.createLineBorder(Color.black));
                     id.add(ids[j]);
                     totalpg.add(totalpgs[j]);
                     totalram.add(totalrams[j]);
                     nrodisco.add(nrodiscos[j]);
                     estado.add(estados[j]);
                  j++;
                }
                
                  //
             id.updateUI();
             totalpg.updateUI();
             totalram.updateUI();
             nrodisco.updateUI();
             estado.updateUI();
             
             
             
             this.procesador.setEditable(true);
		this.procesador.setLineWrap(true);
		this.procesador.setWrapStyleWord(true);
                this.procesador.setFont(new Font("Arial ", Font.BOLD, 12));
                this.procesador.setBorder(BorderFactory.createLineBorder(Color.black));
                this.procesador.setForeground(Color.magenta);
   }             


    private void crearMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMarcoActionPerformed
        //textarea00.setText(textarea00.getText().trim());
        Textarea_Orden.setEnabled(false);
        jLabe_lOrden.setForeground(Color.gray);
        this.jLabel5.setForeground(Color.gray);
        String s=textarea00.getText();
                       int n;
                       
                       if (s.equals("")){
                           System.out.println("Como no coloco nada, se crearan 10 marcos");
                           this.textarea00.setText("10");
                           n=10;
                           crearMarco.setEnabled(false);
                           this.textarea00.setEditable(false);
                           //this.textarea00.setText("");
                            
                       }
                       else
                       {                           
                       n=Integer.parseInt(s);
                       if (n<=0){
                           JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO POSITIVO");
                           this.textarea00.setText("");
                           return;
                       }
                       crearMarco.setEnabled(false);
                       this.textarea00.setEditable(false);
                       //this.textarea00.setText("");
                        }
                       System.out.println("la cantidad de marcos ingresadas es " + n);
                       
        this.Go(n);
        habilitar();
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_crearMarcoActionPerformed

    private void radioButton_opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_opcion1ActionPerformed
        // TODO add your handling code here:
        Textarea_Orden.setEnabled(false);
        jLabe_lOrden.setForeground(Color.gray);
        jLabel15.setForeground(Color.gray);
                    
    }//GEN-LAST:event_radioButton_opcion1ActionPerformed

    private void radioButton_opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_opcion2ActionPerformed
        // TODO add your handling code here:
        Textarea_Orden.setEnabled(true);
        jLabe_lOrden.setForeground(Color.black);
        Textarea_nroPaginas.setText(null);
        
    }//GEN-LAST:event_radioButton_opcion2ActionPerformed

    private void crearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProcesoActionPerformed
        //Textarea_nroPaginas.setText(Textarea_nroPaginas.getText().trim());
           //cont_de_proceso lo puse como variable Global
        //Textarea_nroPaginas.setText(Textarea_nroPaginas.getText().trim());
        String ss=this.Textarea_nroPaginas.getText().trim();
        System.out.println("valor de cantidad de paginas" + ss);
          
        cont_para_paginas_escribir[indice_cont_de_pag]=ss; 
        indice_cont_de_pag++;
           
        if(radioButton_opcion1.isSelected()){   
                  Textarea_Orden.setEnabled(false);
                  this.Textarea_nroPaginas.setText("");
                  if (ss.equals("")){
                           JOptionPane.showMessageDialog(null,"INGRESE CANTIDAD DE PAGINAS");
                           return;
                 }                                        
                 int pags=Integer.parseInt(ss);
                 if ((pags<0)||(pags==0)){
                         JOptionPane.showMessageDialog(null,"INGRESE UN VALOR MAYOR A 0");      
                 }
                 else{
                        //lo comente para ver si andaba el contador y el resto y setenable
                        //System.out.println("antes de crear proceso con %d" + pags);
                       this.manejador.crearProceso(pags, this.Textarea_nombreProceso.getText().trim());
                       
                       this.manejador.ImprimirProcesos();
                       this.manejador.ImprimirMemVirtual();
                       this.manejador.ImprimirMemRAM();                       
                       siguiente.setEnabled(true);
                       ejecutar.setEnabled(true);
                       Textarea_Orden.setEnabled(false);
                       Textarea_nombreProceso.setText("");
                       int j=0;          
                       cont_de_proceso++;
                }
                      
        } 
                  
        
        if(radioButton_opcion2.isSelected()){
            Textarea_Orden.setEnabled(true);
            Textarea_Orden.setText(Textarea_Orden.getText().trim());
           String orden=this.Textarea_Orden.getText();
            if ((ss.equals("")) && (orden.equals(""))) {
            JOptionPane.showMessageDialog(null,"INGRESE NUMERO DE PAGINA Y ORDEN SECUENCIAL");
            return;
        }
                   int pags=Integer.parseInt(this.Textarea_nroPaginas.getText());
                if ((pags<2)){
                        JOptionPane.showMessageDialog(null,"INGRESE PAGINA MAYOR A 2");      
                               
                return;
                }
               
            if (orden.equals("")){
                           JOptionPane.showMessageDialog(null,"INGRESE ORDEN SECUENCIAL");
                           return;
              }         
            
             if (ss.equals("")){
                           JOptionPane.showMessageDialog(null,"INGRESE NUMERO DE PAGINA");
                           return;
              }                        
                            
                               
        else  {
                 
                   String secuencia=this.Textarea_Orden.getText();
                   int n=Integer.parseInt(this.Textarea_nroPaginas.getText());
                   ArrayList<String> listTemp=new ArrayList<>();
                   int[] arreglos_PCpag;
                   String s,k,temp="";
                   int i,g;
                   i=0;
                   if ((n*2)-1 != secuencia.length()){
                    JOptionPane.showMessageDialog(null,"EL NUMERO DE PAGINA NO COINCIDE CON CANTIDAD DE SECUENCIA");
                    return;
                  }

             while(i<=secuencia.length()){
                   if (i<secuencia.length()-1){    
                   if(Character.toString(secuencia.charAt(i)).equals("-")){
                        listTemp.add(temp);
                        //System.out.print("i:_"+i+" temp:_"+temp+" ");
                        temp="";
                     }
                else{
                          temp=temp+Character.toString(secuencia.charAt(i));
                         // System.out.print(temp);
                      }
                   }
                   else{
                    listTemp.add(Character.toString(secuencia.charAt(secuencia.length()-1)));
                    int x=secuencia.length()-1;
                    
                   //System.out.print("i:_"+x+" temp:_"+listTemp.get(listTemp.size()-1)+" ");
                   }
                    i++;
                   }
                   
                  i=0;
                  arreglos_PCpag=new int[listTemp.size()-2];
                  while(i<arreglos_PCpag.length){
                     arreglos_PCpag[i]=Integer.parseInt(listTemp.get(i));
                     //System.out.print("arreglos["+i+"]:_____"+arreglos_PCpag[i]+"\n");
                     i++;
                   }

             //Ahora llamo a crear el proceso...
                    //lo comente para ver si andaba el contador y el resto y setenable
                       //this.manejador.crearProceso_NoSecuencial(n,arreglos_PCpag);
                       this.manejador.crearProceso_NoSecuencial(n,arreglos_PCpag,this.Textarea_nombreProceso.getText().trim());
                       this.manejador.ImprimirProcesos();
                       this.manejador.ImprimirMemVirtual();
                       this.manejador.ImprimirMemRAM();
                       siguiente.setEnabled(true);
                       ejecutar.setEnabled(true);
              cont_de_proceso++;

             
             
             
             }      
             
             
             
    } //a ca cierra el personalizado     
        Textarea_nroPaginas.setText("");
     jLabel_cont_proceso.setText(String.valueOf(cont_de_proceso));
        //jLabel_cont_proceso.setText("");
    }//GEN-LAST:event_crearProcesoActionPerformed

    private void boton_algoritmosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton_algoritmosItemStateChanged
        // TODO add your .handling code here:
            
    }//GEN-LAST:event_boton_algoritmosItemStateChanged

    private void Jbutton_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbutton_ayudaActionPerformed
      FrameAyuda fr=new FrameAyuda();
     
      fr.setVisible(true);
      fr.setLocationRelativeTo(null);
      //this.setVisible(false);
    }//GEN-LAST:event_Jbutton_ayudaActionPerformed

    private void boton_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_manualActionPerformed
        // TODO add your handling code here:
        Frame_manual manual=new Frame_manual();
        manual.setVisible(true);
        manual.setLocationRelativeTo(null);
    }//GEN-LAST:event_boton_manualActionPerformed

    private void jMenu_algoritmoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu_algoritmoItemStateChanged
        //manejador
        
    }//GEN-LAST:event_jMenu_algoritmoItemStateChanged

    private void jMenu_algoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_algoritmoActionPerformed
        // TODO add your handling code here:}
        System.out.print("entro a ejecutar item");
        //this.manejador.Ejecutar();
    }//GEN-LAST:event_jMenu_algoritmoActionPerformed

    private void jMenu_AyudaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu_AyudaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_AyudaItemStateChanged

    private void jMenu_AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_AyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_AyudaActionPerformed

    private void boton_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_abrirActionPerformed
        // TODO add your handling code here:
        this.limpiar();
        
        Mostrar fr=new Mostrar();
        abrirArchivo();
        
      fr.setVisible(true);
      fr.setLocationRelativeTo(null);
        //limpiar.setEnabled(true);
        textarea00.setEditable(true);
        textarea00.setEnabled(true);
        //crearProceso.setEnabled(true);
    }//GEN-LAST:event_boton_abrirActionPerformed

    ////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbutton_ayuda;
    private javax.swing.JTextArea Textarea_Orden;
    private javax.swing.JTextArea Textarea_nombreProceso;
    private javax.swing.JTextArea Textarea_nroPaginas;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton boton_abrir;
    private javax.swing.JComboBox<String> boton_algoritmos;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JButton boton_manual;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton crearMarco;
    private javax.swing.JButton crearProceso;
    private javax.swing.JButton ejecutar;
    private javax.swing.JPanel estado;
    private javax.swing.JPanel id;
    private javax.swing.JLabel jLabe_lOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_cont_proceso;
    private javax.swing.JLabel jLabel_nroDePagina;
    private javax.swing.JLabel jLabel_nroDePagina1;
    private javax.swing.JLabel jLabel_nroDePagina2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenu_Achivo;
    private javax.swing.JMenu jMenu_Ayuda;
    private javax.swing.JMenu jMenu_Edicion;
    private javax.swing.JMenu jMenu_algoritmo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton limpiar;
    private javax.swing.JPanel nrodisco;
    private javax.swing.JTextArea procesador;
    private javax.swing.JRadioButton radioButton_opcion1;
    private javax.swing.JRadioButton radioButton_opcion2;
    private javax.swing.JPanel ram;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextArea textarea00;
    private javax.swing.JTextArea textarea3;
    private javax.swing.JTextArea textarea4;
    private javax.swing.JPanel totalpg;
    private javax.swing.JPanel totalram;
    private javax.swing.JPanel virtualid;
    private javax.swing.JPanel virtualpag;
    // End of variables declaration//GEN-END:variables

public void deshabilitar(){
crearProceso.setEnabled(false);
//abrir.setEnabled(false);
boton_guardar.setEnabled(false);
limpiar.setEnabled(false);
siguiente.setEnabled(false);
ejecutar.setEnabled(false);
       
}

public void habilitar(){
crearProceso.setEnabled(true);
boton_abrir.setEnabled(true);
boton_guardar.setEnabled(true);
limpiar.setEnabled(true);
//siguiente.setEnabled(true);
//ejecutar.setEnabled(true);
}

public JTextArea getTextarea_nombreProceso(){
//Textarea_nombreProceso.getText();
return Textarea_nombreProceso;
}


public JTextArea getTxtNombre() { return procesador; }

public void setTxtNombre(JTextArea textarea2) {
    this.procesador = textarea2;
}


}



